### ISSUE TITLE
Is hourly billing supported ? 

### ISSUE THREAD

**Issue by smoser-ibm** [cloudfoundry/bosh-softlayer-cpi#118]
Hi bosh-sl-cpi team, 

I was trying to find a way to provision my VMs using hourly billing, but I was unable to do so. Am I missing something or isnt that supported yet ? 
If not supported yet, I would expect that I can define this as a global setting (all VMs hourly OR all VMs monthly) - that would be good enough for the start. Thanks for considering this.

**Comment by mattcui** [comment]
It's supported certainly. You just need to specify ```HourlyBillingFlag: true``` in ```cloud_properties``` section, for examples:

https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/blob/master/docs/sl-bosh.yml#L25

**Comment by sykesm** [comment]
This is an example of where the documentation needs improvement. Unless you look through the examples or the code, you don't know what cloud properties are available in which contexts and how they impact the CPI.

I'd very much like to see more than example manifests in the `docs` directory of the CPI release.

**Comment by maximilien** [comment]
Guys, @sykesm and @smoser-ibm,

This is no different than many OSS or software projects. Docs need improvement.

Beating the drum on this issue feels to me you guys have some kind of ulterior motive here.

Find you pointed this out. We'll address it or feel free to submit a PR.

**Comment by sykesm** [comment]
I think you're seeing our frustration bleeding through. We've been spending a lot of time trying to use the CPI to deploy Cloud Foundry in CI environments and feeling pain.

For doc, I would be happy if the documentation clearly called out each of the cloud properties for SoftLayer, described what it does, whether or not it's optional, and why it's needed.  For example, why would the cpi need to know the 'bosh ip'?  Why is it required for a deployment but not for bosh-init? I can hazard a guess from the code but it would be just that - a guess.

So, instead of hijacking this issue, I'm happy to open a separate issue related to documentation. Simon's issue has already been answered so this should probably be closed.

**Comment by maximilien** [comment]
Yup, go ahead. We will address this. @jianqui has been sharing docs via email so it's time we add it formally to the project

**Comment by maximilien** [comment]
@jianqiu has a fix for this. I've reviewed it and need to decide where to put it. Look for a fix/release soon.

**Comment by maximilien** [comment]
@jianqiu I believe this was done. Closing. Please re-open or open new specific issue if anyone thinks something is missing.
