### ISSUE TITLE
Unable to $bosh ssh to other VMs

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry/bosh-softlayer-cpi#138]
Steps to reproduce:

```
$bosh login <directorURL>
$bosh download manifest <deployment-name> /tmp/manifest.yml
$bosh deployment /tmp/manifest.yml
$bosh ssh <job_name> <instance_id>
```

I get the following output in my test ...

```
Acting as user 'admin' on deployment 'flintstone-hkg02-diego' on 'bosh'
Target deployment is `flintstone-hkg02-diego'

Setting up ssh artifacts

Director task 565

Task 565 done
Starting interactive shell on job database_z1/0
ssh: connect to host 161.202.52.50 port 22: Operation timed out

Cleaning up ssh artifacts

Director task 566

Task 566 done
```

This now just hangs there indefinitely and does not connect to the VM.

I have not tried the options `--gateway_host` `--gateway_user` `--gateway_identity_file` as The connection to the director seems to work but the further connection is failing.

At the moment we are required to use the bosh director VM as a jump box.  Logging into the bosh director and then logging into the VMs from there.  But the bosh ssh should be able to tunnel through.

Initially reported by @andrew-edgar in the `bosh-softlayer-cpi-release` project.

**Comment by cppforlife** [comment]
What is 161.202.52.50?

**Comment by sykesm** [comment]
This is behavior is due to a few things:

1. The resource pool definition connected the machine to the public and private networks
2. When a machine is connected to both networks, the public network is the default route (default gateway)
3. The IP associated with the default route is returned to the director as the address
4. The bosh director uses the address associated with the default route as the ssh target
5. The vyatta firewall used on public networks disables ssh access to VMs

If the resource pool were configured with `PrivateNetworkOnlyFlag: true` in the cloud properties, the VM would only be attached to the private network and then the private IP would be reported to bosh. This should result in a functional `bosh ssh`.

Note that when you don't have a public IP, you need to make sure NAT is enabled on the vyatta so you can reach public internet addresses from the VMs.

**Comment by mattcui** [comment]
To address this issue thoroughly, we need to support manual networking and specify private networking as the default one. @jianqiu is working on this, will deliver a dev build soon.

**Comment by sykesm** [comment]
Actually you should model the public and private networks explicitly and allow users to connect them to jobs and declare which is the default. All of this was part of the spike referenced in #135.

If you only state that private networking is the default, you'll have issues with routing and you will require all users to enable NAT on their vyatta/fortigate VLAN gateways.

**Comment by mattcui** [comment]
@sykesm Thanks for the detailed explanation, we understood now. Thanks.

**Comment by maximilien** [comment]
I am closing this and assuming all info is correctly documented and being implemented.
